baseURL = "http://www.wesleyreisz.com/getting_started_with_containerization"
languageCode = "en-us"
title = "Introduction to Containers and Containerization"
enableGitInfo = true
description = "Workshop on containerization"
publishDir = "docs"

[[menu.main]]
name = "Home"
url = "/"
weight = 1